### ISSUE TITLE
Writing test files using on pytest

### ISSUE THREAD

**Issue by athulvis** [project-wavelets/JazzHands#5]
It is necessary to write the test files with pytest module which is compatible with Astropy

**Comment by avivajpeyi** [comment]
Is anyone working on this? Id love to jump in and help out with this! :D

**Comment by tzdwi** [comment]
Not sure if anyone is actively on this at the moment, so feel free!

Best,

Trevor Dorn-Wallenstein
University of Washington
Astronomy Department
he/him

**Comment by athulvis** [comment]
I am working on it. Sorry I didn't notice the comment here. I am familiar, but not much experienced in pytest. I submitted a [PR with test](https://github.com/tzdwi/JazzHands/pull/12) on utility.py. @avivajpeyi please correct and update it.
